[package]
name = "kiri"
version = "0.1.0"
authors = ["nanikamado <nanikamado@gmail.com>"]
edition = "2021"

[dependencies]
libc = "0.2.138"
log = "0.4.17"
env_logger = "0.10.0"
evdev = "0.12.1"
evdev-keys = { git = "https://github.com/nanikamado/evdev-keys", rev = "a67ea24" }
rustc-hash = "1.1.0"
